from typing import Protocol
from src.api.tokens import APIToken


class TokenRepository(Protocol):
    """Persistence contract for API tokens."""

    def create_token(self, username: str, duration_mn: int) -> APIToken: ...
    def get_token(self, token: str) -> APIToken: ...
    def list_active_tokens(self) -> list[dict[str, str]]: ...
    def delete_expired_tokens(self) -> None: ...
